// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVLhBvvr1Of6_A7InUfvjmXZDuO7FkGyE',
    appId: '1:246503400236:web:8ca70102a2ea09bfd48289',
    messagingSenderId: '246503400236',
    projectId: 'weatherapp-f7737',
    authDomain: 'weatherapp-f7737.firebaseapp.com',
    storageBucket: 'weatherapp-f7737.appspot.com',
    measurementId: 'G-T6N4M4ZRBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzEynra7TYwgJE-2hRG4U3ksPEQsp1bjU',
    appId: '1:246503400236:android:d521c5a728d13154d48289',
    messagingSenderId: '246503400236',
    projectId: 'weatherapp-f7737',
    storageBucket: 'weatherapp-f7737.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS2BhJu8Y0XbkEgw58-zbj_hPdMDNN-TA',
    appId: '1:246503400236:ios:0e2d5775ed3d87b7d48289',
    messagingSenderId: '246503400236',
    projectId: 'weatherapp-f7737',
    storageBucket: 'weatherapp-f7737.appspot.com',
    iosClientId: '246503400236-kqljfo17u16kbbd6f1jl4nmdld9qmaan.apps.googleusercontent.com',
    iosBundleId: 'com.example.share',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS2BhJu8Y0XbkEgw58-zbj_hPdMDNN-TA',
    appId: '1:246503400236:ios:0e2d5775ed3d87b7d48289',
    messagingSenderId: '246503400236',
    projectId: 'weatherapp-f7737',
    storageBucket: 'weatherapp-f7737.appspot.com',
    iosClientId: '246503400236-kqljfo17u16kbbd6f1jl4nmdld9qmaan.apps.googleusercontent.com',
    iosBundleId: 'com.example.share',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVLhBvvr1Of6_A7InUfvjmXZDuO7FkGyE',
    appId: '1:246503400236:web:8c24892002c1ac7ed48289',
    messagingSenderId: '246503400236',
    projectId: 'weatherapp-f7737',
    authDomain: 'weatherapp-f7737.firebaseapp.com',
    storageBucket: 'weatherapp-f7737.appspot.com',
    measurementId: 'G-RH32Q8857H',
  );
}
